services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    restart: on-failure:1
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    command: yarn run dev
    develop:
      watch:
        - path: ./src
          action: sync
          target: /app/src
        - path: ./public
          action: sync
          target: /app/public
        - path: ./.env
          action: sync
          target: /app/.env
        - path: package.json
          action: rebuild